# Generated by Django 4.1.3 on 2022-11-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ruta',
            name='placa',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
