# Generated by Django 4.1.3 on 2022-12-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_ruta_number_ruta_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='empresa',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
