# Generated by Django 4.1.3 on 2022-12-02 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_conductor_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miapp.empresa'),
        ),
    ]
