# Generated by Django 4.1.3 on 2022-12-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_conductor_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nombre',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_empresa',
            field=models.CharField(default=1, max_length=40),
        ),
    ]
