# Generated by Django 4.1.3 on 2022-12-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_rename_nombre_empresa_nombre_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='nombre_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default='nombre', max_length=40),
        ),
    ]
