# Generated by Django 4.1.3 on 2022-12-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_remove_empresa_nombre_empresa_empresa_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
