# Generated by Django 4.1.3 on 2022-12-12 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2022, 12, 12, 16, 6, 59, 606901))),
                ('approved_comment', models.BooleanField(default=False)),
                ('condcuctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.conductor')),
            ],
        ),
    ]
