# Generated by Django 4.1.3 on 2022-12-12 21:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_alter_avatar_imagen_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='condcuctor',
        ),
        migrations.AddField(
            model_name='comment',
            name='conductor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miapp.conductor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 16, 44, 14, 234891)),
        ),
    ]
