# Generated by Django 4.1.3 on 2022-12-13 02:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_remove_comment_condcuctor_comment_conductor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miapp.conductor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 21, 23, 49, 610557)),
        ),
    ]
