# Generated by Django 4.1.3 on 2022-12-13 02:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0017_alter_comment_created_date_alter_ruta_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 21, 57, 19, 111230)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.conductor'),
        ),
    ]
