# Generated by Django 4.1.3 on 2022-12-13 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0020_alter_comment_created_date_alter_ruta_conductor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='conductor',
            new_name='conductor1',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 22, 1, 19, 314702)),
        ),
    ]
