# Generated by Django 4.1.3 on 2022-12-13 03:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0021_rename_conductor_ruta_conductor1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 22, 3, 46, 111051)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='conductor1',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.conductor'),
        ),
    ]
