# Generated by Django 4.1.3 on 2022-12-13 03:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0022_alter_comment_created_date_alter_ruta_conductor1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='conductor1',
        ),
        migrations.AddField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='miapp.conductor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 22, 7, 15, 611033)),
        ),
    ]
