# Generated by Django 4.1.3 on 2022-12-13 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0024_alter_comment_created_date_alter_ruta_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='conductor',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 12, 23, 29, 13, 65584)),
        ),
    ]
