# Generated by Django 4.1.3 on 2022-12-13 05:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0031_alter_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miapp.conductor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 0, 21, 2, 116061)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='placa',
            field=models.CharField(max_length=40),
        ),
    ]
